//
//  AvailableFonts.swift
//  Lateral Thinking
//
//  Created by Paul Wood on 7/21/19.
//  Copyright © 2019 Paul Wood. All rights reserved.
//

import Foundation

public enum AvailableFonts: String, CaseIterable {
  
  public typealias RawValue = String
  
  //case NotoSerif
  case DevanagariSangamMN = "Devanagari Sangam MN"
  case Galvji = "Galvji"
  case AvenirNext = "Avenir Next"
  case KohinoorGujarati = "Kohinoor Gujarati"
  case KohinoorDevanagari = "Kohinoor Devanagari"
  case TimesNewRoman = "Times New Roman"
  case GillSans = "Gill Sans"
  case Kailasa = "Kailasa"
  case BradleyHand = "Bradley Hand"
  case PingFangHK = "PingFang HK"
  case SavoyeLET = "Savoye LET"
  case TrebuchetMS = "Trebuchet MS"
  case Baskerville = "Baskerville"
  case Futura = "Futura"
  case ArialHebrew = "Arial Hebrew"
  case Bodoni72 = "Bodoni 72"
  case HoeflerText = "Hoefler Text"
  case Optima = "Optima"
  case DINCondensed = "DIN Condensed"
  case NotoNastaliqUrdu = "Noto Nastaliq Urdu"
  case Charter = "Charter"
  case HeitiTC = "Heiti TC"
  case GeezaPro = "Geeza Pro"
  case BodoniOrnaments = "Bodoni Ornaments"
  case KohinoorTelugu = "Kohinoor Telugu"
  case HelveticaNeue = "Helvetica Neue"
  case PartyLET = "Party LET"
  case Symbol = "Symbol"
  case BanglaSangamMN = "Bangla Sangam MN"
  case HiraginoSans = "Hiragino Sans"
  case HiraginoMaruGothicProN = "Hiragino Maru Gothic ProN"
  case Cochin = "Cochin"
  case EuphemiaUCAS = "Euphemia UCAS"
  case AcademyEngravedLET = "Academy Engraved LET"
  case Helvetica = "Helvetica"
  case AmericanTypewriter = "American Typewriter"
  case Didot = "Didot"
  case CourierNew = "Courier New"
  case NotoSansKannada = "Noto Sans Kannada"
  case Courier = "Courier"
  case Rockwell = "Rockwell"
  case Palatino = "Palatino"
  case MalayalamSangamMN = "Malayalam Sangam MN"
  case Mishafi = "Mishafi"
  case SnellRoundhand = "Snell Roundhand"
  case AvenirNextCondensed = "Avenir Next Condensed"
  case HeitiSC = "Heiti SC"
  case Damascus = "Damascus"
  case LaoSangamMN = "Lao Sangam MN"
  case Papyrus = "Papyrus"
  case Copperplate = "Copperplate"
  case Thonburi = "Thonburi"
  case SinhalaSangamMN = "Sinhala Sangam MN"
  case KohinoorBangla = "Kohinoor Bangla"
  case ChalkboardSE = "Chalkboard SE"
  case Noteworthy = "Noteworthy"
  case Farah = "Farah"
  case NotoSansOriya = "Noto Sans Oriya"
  case Arial = "Arial"
  case Georgia = "Georgia"
  case HiraginoMinchoProN = "Hiragino Mincho ProN"
  case Verdana = "Verdana"
  case AppleColorEmoji = "Apple Color Emoji"
  case DINAlternate = "DIN Alternate"
  case NotoSansMyanmar = "Noto Sans Myanmar"
  case PingFangSC = "PingFang SC"
  case Chalkduster = "Chalkduster"
  case PingFangTC = "PingFang TC"
  case TamilSangamMN = "Tamil Sangam MN"
  case KhmerSangamMN = "Khmer Sangam MN"
  case AppleSDGothicNeo = "Apple SD Gothic Neo"
  case ArialRoundedMTBold = "Arial Rounded MT Bold"
  case MuktaMahee = "Mukta Mahee"
  case AlNile = "Al Nile"
  case Bodoni72Smallcaps = "Bodoni 72 Smallcaps"
  case MarkerFelt = "Marker Felt"
  case AppleSymbols = "Apple Symbols"
  case Menlo = "Menlo"
  case Avenir = "Avenir"
  case TeluguSangamMN = "Telugu Sangam MN"
  case Bodoni72Oldstyle = "Bodoni 72 Oldstyle"
  case MyanmarSangamMN = "Myanmar Sangam MN"
  case Kefa = "Kefa"
  case ZapfDingbats = "Zapf Dingbats"
  case Zapfino = "Zapfino"
  case NotoSansZawgyi = "Noto Sans Zawgyi"
}
